version: '3.9'
services:
  mysql-employe:
    container_name: mysql-employe-container-0
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - '3305:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=dione1234
      - MYSQL_DATABASE=ms_employe
    networks:
      employenet:


  php-myadmin-mundia:
    container_name: phpmyadmin-employe-0
    depends_on:
      - mysql-employe
    image: phpmyadmin/phpmyadmin
    restart: no
    ports:
      - '1010:80'
    environment:
      - PMA_HOST=mysql-employe-container-0
      - MYSQL_ROOT_PASSWORD=dione1234
    networks:
      employenet:



  springboot-msproduct:
    container_name: springboot-msemploye-container-0
    image: dioneousseynou/java-spring:v1
    ports:
      - '1020:1020'
    environment:
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://mysql-employe-container-0:3306/ms_employe?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=dione1234
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      employenet:





networks:
  employenet:
    driver: bridge
