apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-employe-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-employe-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
